run: complie execute

complie:
	g++ Task_B.cpp -o Task_B.exe -Wall
	g++ Task_C.cpp -o Task_C.exe -Wall
	g++ Task_D.cpp -o Task_D.exe -Wall
	g++ Task_E.cpp -o Task_E.exe -Wall
	g++ Task_F.cpp -o Task_F.exe -Wall

execute:
	./Task_B.exe
	./Task_C.exe
	./Task_D.exe
	./Task_E.exe
	./Task_F.exe

clean:
	rm -f *.exe